-- Create roles table and seed rows
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE
);

-- Seed default roles if not exists
INSERT INTO roles (name) SELECT 'CUSTOMER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='CUSTOMER');
INSERT INTO roles (name) SELECT 'RECEPTIONIST' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='RECEPTIONIST');
INSERT INTO roles (name) SELECT 'DENTIST' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='DENTIST');
INSERT INTO roles (name) SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ADMIN');
INSERT INTO roles (name) SELECT 'PATIENT' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='PATIENT');

