name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Run unit tests (fast)
        run: mvn -B -V -DskipITs=true test
        env:
          MAVEN_OPTS: -Xms256m -Xmx1024m

      - name: Upload unit test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

  integration:
    name: Integration Tests (containerized)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Run integration tests (Testcontainers)
        # Runs full test suite including Testcontainers integration tests
        run: mvn -B -V -DskipTests=false test
        env:
          MAVEN_OPTS: -Xms256m -Xmx1024m

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-integration
          path: target/surefire-reports
